using System.Runtime.InteropServices;


namespace GTASessionBot.Windows_Libraries
{
    [StructLayout(LayoutKind.Sequential)]
    struct HardwareInput
    {

        /// <summary>
        /// The message generated by the input hardware.
        /// </summary>
        public int uMsg;


        /// <summary>
        /// The low-order word of the lParam parameter for uMsg.
        /// </summary>
        public short wParamL;


        /// <summary>
        /// The high-order word of the lParam parameter for uMsg.
        /// </summary>
        public short wParamH;
    }
}
